workflows:
  android-workflow:
    name: Ole Glory PaintPro Android
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      
      vars:
        PACKAGE_NAME: "com.oleglory.paintpro"
        
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $FLUTTER_ROOT/.pub-cache
        
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
          
      - name: Flutter analyze
        script: |
          flutter analyze
          
      - name: Build APK
        script: |
          flutter build apk --release
          
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/**/*.aab
      
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
          
      # Uncomment if you want to publish to Google Play
      # google_play:
      #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      #   track: internal
      #   submit_as_draft: true
